# Generated by Django 3.2.8 on 2021-10-10 05:58

from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('mission', models.CharField(max_length=100, verbose_name='Mission Title')),
                ('content1', models.TextField(max_length=300)),
                ('vision', models.CharField(max_length=100, verbose_name='Vision Title')),
                ('content2', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Blog Title')),
                ('slug', models.SlugField(unique=True)),
                ('blg_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('blg_image1', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image1')),
                ('blg_image2', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image2')),
                ('user', models.CharField(max_length=100, verbose_name='Posted By')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Career Image')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Career',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'What Drive Us',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('pst_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=200, verbose_name='Home Address')),
                ('driver', models.CharField(max_length=100, verbose_name='Drivers License No')),
                ('nin', models.CharField(max_length=100, verbose_name='NIN No')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='FourApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=300)),
                ('app_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'FourApp',
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('pst_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('from_where', models.CharField(max_length=200, verbose_name='From Where')),
                ('to_where', models.CharField(max_length=200, verbose_name='Where arae you going')),
                ('passng', models.IntegerField(verbose_name='No of Passenger')),
                ('da_ti', models.CharField(max_length=200, verbose_name='Date/Time')),
            ],
            options={
                'verbose_name_plural': 'Hire',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField(verbose_name='Privacy Policy')),
                ('content2', tinymce.models.HTMLField(verbose_name='Terms & Conditions')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Privacy',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('pst_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('date', models.CharField(max_length=200, verbose_name='Date/Time')),
                ('pickoff', models.CharField(max_length=200, verbose_name='Pickoff Location')),
                ('dropoff', models.CharField(max_length=100, verbose_name='Dropoff Location')),
                ('drop_time', models.CharField(max_length=200, verbose_name='Date/Time')),
                ('bus_no', models.CharField(max_length=100, verbose_name='Bus Serial No')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Support2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Support Content',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Founder Nmae')),
                ('title', models.CharField(max_length=100, verbose_name='Designation')),
                ('abt_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('body', tinymce.models.HTMLField(verbose_name='Content')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='frontend.blog')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
