# Generated by Django 3.2.8 on 2021-10-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
