# Generated by Django 3.2.8 on 2021-10-06 04:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_about_what_is_drivig_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('pst_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=200, verbose_name='Home Address')),
                ('driver', models.CharField(max_length=100, verbose_name='Drivers License No')),
                ('nin', models.CharField(max_length=100, verbose_name='NIN No')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Driver',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='what_is_drivig_content',
            field=tinymce.models.HTMLField(verbose_name='What is Driving Us Content'),
        ),
    ]
