# Generated by Django 3.2.8 on 2021-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20211006_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('pst_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('date', models.DateTimeField()),
                ('pickoff', models.CharField(max_length=200, verbose_name='Pickoff Location')),
                ('dropoff', models.CharField(max_length=100, verbose_name='Dropoff Location')),
                ('drop_time', models.DateField()),
                ('bus_no', models.CharField(max_length=100, verbose_name='Bus Serial No')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Support',
            },
        ),
    ]
