# Generated by Django 3.2.8 on 2021-10-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pst_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='blg_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blg_image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blg_image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Posted By'),
        ),
    ]
