# Generated by Django 3.2.8 on 2021-10-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='drop_time',
        ),
    ]
