# Generated by Django 3.2.8 on 2021-10-06 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_support_drop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='drop_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
