# Generated by Django 3.2.8 on 2021-10-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20211010_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pst_title',
            new_name='title',
        ),
    ]
