# Generated by Django 3.2.8 on 2021-10-06 12:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_support_drop_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Support Content',
            },
        ),
    ]
