# Generated by Django 3.2.8 on 2021-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_support2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('pst_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('from_where', models.CharField(max_length=200, verbose_name='From Where')),
                ('to_where', models.CharField(max_length=200, verbose_name='Where arae you going')),
                ('passng', models.IntegerField(verbose_name='No of Passenger')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hire',
            },
        ),
    ]
