# Generated by Django 3.2.8 on 2021-10-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drive',
        ),
    ]
