# Generated by Django 3.2.8 on 2021-10-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_hire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='created',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='modified',
        ),
    ]
