# Generated by Django 3.2.8 on 2021-10-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20211006_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blg_image1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blg_image2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image2'),
        ),
    ]
