# Generated by Django 3.2.8 on 2021-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20211006_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
