# Generated by Django 3.2.8 on 2021-10-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_comment_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
