# Generated by Django 3.2.8 on 2021-10-06 19:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20211006_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Career Image')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Career',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='blg_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blg_image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image1'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blg_image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image2'),
        ),
    ]
