# Generated by Django 3.2.8 on 2021-10-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20211006_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='da_ti',
            field=models.CharField(default=1, max_length=200, verbose_name='Date/Time'),
            preserve_default=False,
        ),
    ]
