# Generated by Django 3.2.8 on 2021-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_hire_da_ti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='drop_time',
            field=models.DateTimeField(),
        ),
    ]
