# Generated by Django 3.2.8 on 2021-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_alter_support_drop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date',
            field=models.CharField(max_length=200, verbose_name='Date/Time'),
        ),
        migrations.AlterField(
            model_name='support',
            name='drop_time',
            field=models.CharField(max_length=200, verbose_name='Date/Time'),
        ),
    ]
