# Generated by Django 3.2.8 on 2021-10-06 21:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='content2',
            field=tinymce.models.HTMLField(default=1, verbose_name='Terms & Conditions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privacy',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Privacy Policy'),
        ),
    ]
